process.env.DATABASE_URL =
  'postgresql://resolvex_dev:resolvex_dev_password@localhost:5432/resolvex_dev?schema=public';
process.env.JWT_SECRET = 'test_jwt_secret_for_resolvex_phase_1';
process.env.JWT_EXPIRES_IN = '1h';
process.env.STORAGE_PROVIDER = 'local';
process.env.LOCAL_STORAGE_PATH = './tmp/test-evidence';
process.env.MAX_EVIDENCE_FILE_SIZE_BYTES = '10485760';
process.env.EVIDENCE_UPLOAD_URL_TTL_SECONDS = '600';
process.env.EVIDENCE_DOWNLOAD_URL_TTL_SECONDS = '300';
process.env.AI_SERVICE_URL = 'http://localhost:8000';
process.env.AI_SERVICE_TIMEOUT_MS = '15000';
process.env.AI_SERVICE_RETRY_ATTEMPTS = '2';
process.env.AI_SERVICE_RETRY_BACKOFF_MS = '0';
process.env.AUTH_RATE_LIMIT_MAX = '1000';
process.env.UPLOAD_RATE_LIMIT_MAX = '1000';
