export enum CaseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AWAITING_MERCHANT = 'AWAITING_MERCHANT',
  EVIDENCE_PROCESSING = 'EVIDENCE_PROCESSING',
  UNDER_EVALUATION = 'UNDER_EVALUATION',
  HUMAN_REVIEW = 'HUMAN_REVIEW',
  RESOLVED = 'RESOLVED',
  APPEALED = 'APPEALED',
  CLOSED = 'CLOSED',
}
